//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Core.Objects;

namespace GZAAT.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Contragent> T_Contragent { get; set; }
        public DbSet<T_Debt> T_Debt { get; set; }
        public DbSet<T_Mobile> T_Mobile { get; set; }
        public DbSet<T_DebtDetail> T_DebtDetail { get; set; }
        public DbSet<T_SMS> T_SMS { get; set; }
        public DbSet<T_SMSDetail> T_SMSDetail { get; set; }
        public DbSet<VW_DebtDetail_List> VW_DebtDetail_List { get; set; }
        public DbSet<VW_SMSDetail_List> VW_SMSDetail_List { get; set; }
        public DbSet<T_DebtDetailLog> T_DebtDetailLog { get; set; }
        public DbSet<T_SMSDetailLog> T_SMSDetailLog { get; set; }
    
        public virtual ObjectResult<SP_Debt_GetForSend_Result> SP_Debt_GetForSend()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Debt_GetForSend_Result>("SP_Debt_GetForSend");
        }
    
        public virtual ObjectResult<SP_SMS_GetForSend_Result> SP_SMS_GetForSend()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SMS_GetForSend_Result>("SP_SMS_GetForSend");
        }
    
        public virtual int SP_Debt_Save(Nullable<int> id, Nullable<int> mobileID, Nullable<byte> statusID)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var mobileIDParameter = mobileID.HasValue ?
                new ObjectParameter("mobileID", mobileID) :
                new ObjectParameter("mobileID", typeof(int));
    
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("statusID", statusID) :
                new ObjectParameter("statusID", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Debt_Save", idParameter, mobileIDParameter, statusIDParameter);
        }
    
        public virtual int SP_SMS_Save(Nullable<int> id, Nullable<int> mobileID, Nullable<byte> statusID)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var mobileIDParameter = mobileID.HasValue ?
                new ObjectParameter("mobileID", mobileID) :
                new ObjectParameter("mobileID", typeof(int));
    
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("statusID", statusID) :
                new ObjectParameter("statusID", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SMS_Save", idParameter, mobileIDParameter, statusIDParameter);
        }
    
        public virtual int SP_T_SMSDetailLog_Save(Nullable<int> smsID, Nullable<int> mobileID, string url, string response, string exception)
        {
            var smsIDParameter = smsID.HasValue ?
                new ObjectParameter("smsID", smsID) :
                new ObjectParameter("smsID", typeof(int));
    
            var mobileIDParameter = mobileID.HasValue ?
                new ObjectParameter("mobileID", mobileID) :
                new ObjectParameter("mobileID", typeof(int));
    
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            var responseParameter = response != null ?
                new ObjectParameter("response", response) :
                new ObjectParameter("response", typeof(string));
    
            var exceptionParameter = exception != null ?
                new ObjectParameter("exception", exception) :
                new ObjectParameter("exception", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_T_SMSDetailLog_Save", smsIDParameter, mobileIDParameter, urlParameter, responseParameter, exceptionParameter);
        }
    
        public virtual int SP_T_DebtDetailLog_Save(Nullable<int> debtID, Nullable<int> mobileID, string url, string response, string exception)
        {
            var debtIDParameter = debtID.HasValue ?
                new ObjectParameter("debtID", debtID) :
                new ObjectParameter("debtID", typeof(int));
    
            var mobileIDParameter = mobileID.HasValue ?
                new ObjectParameter("mobileID", mobileID) :
                new ObjectParameter("mobileID", typeof(int));
    
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            var responseParameter = response != null ?
                new ObjectParameter("response", response) :
                new ObjectParameter("response", typeof(string));
    
            var exceptionParameter = exception != null ?
                new ObjectParameter("exception", exception) :
                new ObjectParameter("exception", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_T_DebtDetailLog_Save", debtIDParameter, mobileIDParameter, urlParameter, responseParameter, exceptionParameter);
        }
    }
}
