//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GZAAT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Contragent
    {
        public T_Contragent()
        {
            this.T_Debt = new HashSet<T_Debt>();
        }
    
        public int ID { get; set; }
        public string Code1C { get; set; }
        public string Name { get; set; }
        public string PersonalNumber { get; set; }
    
        public virtual ICollection<T_Debt> T_Debt { get; set; }
    }
}
