//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GZAAT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DebtDetail
    {
        public T_DebtDetail()
        {
            this.T_DebtDetailLog = new HashSet<T_DebtDetailLog>();
        }
    
        public int ID { get; set; }
        public int MobileID { get; set; }
        public byte RelationTypeID { get; set; }
        public byte StatusID { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public byte TryCount { get; set; }
    
        public virtual T_Debt T_Debt { get; set; }
        public virtual T_Mobile T_Mobile { get; set; }
        public virtual ICollection<T_DebtDetailLog> T_DebtDetailLog { get; set; }
    }
}
