//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GZAAT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Mobile
    {
        public T_Mobile()
        {
            this.T_DebtDetail = new HashSet<T_DebtDetail>();
            this.T_SMSDetail = new HashSet<T_SMSDetail>();
        }
    
        public int ID { get; set; }
        public string Mobile { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<T_DebtDetail> T_DebtDetail { get; set; }
        public virtual ICollection<T_SMSDetail> T_SMSDetail { get; set; }
    }
}
