//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GZAAT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SMS
    {
        public T_SMS()
        {
            this.T_SMSDetail = new HashSet<T_SMSDetail>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Message { get; set; }
    
        public virtual ICollection<T_SMSDetail> T_SMSDetail { get; set; }
    }
}
