//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GZAAT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SMSDetailLog
    {
        public int ID { get; set; }
        public int SMSID { get; set; }
        public int MobileID { get; set; }
        public System.DateTime Date { get; set; }
        public string URL { get; set; }
        public string Response { get; set; }
        public string Exception { get; set; }
    
        public virtual T_SMSDetail T_SMSDetail { get; set; }
    }
}
