//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ApplicationResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1C Code.
        /// </summary>
        internal static string Code1C {
            get {
                return ResourceManager.GetString("Code1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        internal static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt.
        /// </summary>
        internal static string Debt {
            get {
                return ResourceManager.GetString("Debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt List.
        /// </summary>
        internal static string DebtList {
            get {
                return ResourceManager.GetString("DebtList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor List.
        /// </summary>
        internal static string DebtorList {
            get {
                return ResourceManager.GetString("DebtorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        internal static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Mobile.
        /// </summary>
        internal static string FatherMobile {
            get {
                return ResourceManager.GetString("FatherMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Period.
        /// </summary>
        internal static string GeneratePeriod {
            get {
                return ResourceManager.GetString("GeneratePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Debt List From 1C.
        /// </summary>
        internal static string GetDebtListFrom1C {
            get {
                return ResourceManager.GetString("GetDebtListFrom1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Text:.
        /// </summary>
        internal static string MessageTextLable {
            get {
                return ResourceManager.GetString("MessageTextLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Text field is required.
        /// </summary>
        internal static string MessageTextRequiredErrorText {
            get {
                return ResourceManager.GetString("MessageTextRequiredErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Owner.
        /// </summary>
        internal static string MobileOwner {
            get {
                return ResourceManager.GetString("MobileOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Field is required.
        /// </summary>
        internal static string MobileRequiredErrorText {
            get {
                return ResourceManager.GetString("MobileRequiredErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phones.
        /// </summary>
        internal static string MobilesLable {
            get {
                return ResourceManager.GetString("MobilesLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter 1 mobile per line..
        /// </summary>
        internal static string MobilesPeerLineToolTip {
            get {
                return ResourceManager.GetString("MobilesPeerLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        internal static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Mobile.
        /// </summary>
        internal static string MotherMobile {
            get {
                return ResourceManager.GetString("MotherMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent 1 First  Name.
        /// </summary>
        internal static string Parent1FirstName {
            get {
                return ResourceManager.GetString("Parent1FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent 1 Last Name.
        /// </summary>
        internal static string Parent1LastName {
            get {
                return ResourceManager.GetString("Parent1LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent 1 Mobile.
        /// </summary>
        internal static string Parent1Mobile {
            get {
                return ResourceManager.GetString("Parent1Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent 2 First Name.
        /// </summary>
        internal static string Parent2FirstName {
            get {
                return ResourceManager.GetString("Parent2FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent 2 Last Name.
        /// </summary>
        internal static string Parent2LastName {
            get {
                return ResourceManager.GetString("Parent2LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent 2 Mobile.
        /// </summary>
        internal static string Parent2Mobile {
            get {
                return ResourceManager.GetString("Parent2Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Number.
        /// </summary>
        internal static string PersonalNumber {
            get {
                return ResourceManager.GetString("PersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Owner.
        /// </summary>
        internal static string RelationTypeColumnHeaderText {
            get {
                return ResourceManager.GetString("RelationTypeColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save For Send.
        /// </summary>
        internal static string SaveForSend {
            get {
                return ResourceManager.GetString("SaveForSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Date:.
        /// </summary>
        internal static string SendDateLable {
            get {
                return ResourceManager.GetString("SendDateLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Date field is required.
        /// </summary>
        internal static string SendDateRequiredErrorText {
            get {
                return ResourceManager.GetString("SendDateRequiredErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Date.
        /// </summary>
        internal static string SentDate {
            get {
                return ResourceManager.GetString("SentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Period.
        /// </summary>
        internal static string SentPeriod {
            get {
                return ResourceManager.GetString("SentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static SMS.
        /// </summary>
        internal static string StaticSMS {
            get {
                return ResourceManager.GetString("StaticSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Mobile.
        /// </summary>
        internal static string StudentMobile {
            get {
                return ResourceManager.GetString("StudentMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        internal static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Count.
        /// </summary>
        internal static string TryCount {
            get {
                return ResourceManager.GetString("TryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Excel.
        /// </summary>
        internal static string UploadExcel {
            get {
                return ResourceManager.GetString("UploadExcel", resourceCulture);
            }
        }
    }
}
