//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadFilter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadFilter.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ექსფრეშენის დამატება.
        /// </summary>
        internal static string AddExpressionToolTip {
            get {
                return ResourceManager.GetString("AddExpressionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჯგუფის დამატება.
        /// </summary>
        internal static string AddGroupToolTip {
            get {
                return ResourceManager.GetString("AddGroupToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაფილტრვა.
        /// </summary>
        internal static string ApplyButtonText {
            get {
                return ResourceManager.GetString("ApplyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to და.
        /// </summary>
        internal static string BetweenDelimeterText {
            get {
                return ResourceManager.GetString("BetweenDelimeterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შორის.
        /// </summary>
        internal static string FilterFunctionBetween {
            get {
                return ResourceManager.GetString("FilterFunctionBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეიცავს.
        /// </summary>
        internal static string FilterFunctionContains {
            get {
                return ResourceManager.GetString("FilterFunctionContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არშეიცავს.
        /// </summary>
        internal static string FilterFunctionDoesNotContain {
            get {
                return ResourceManager.GetString("FilterFunctionDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მთავრდება.
        /// </summary>
        internal static string FilterFunctionEndsWith {
            get {
                return ResourceManager.GetString("FilterFunctionEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტოლია.
        /// </summary>
        internal static string FilterFunctionEqualTo {
            get {
                return ResourceManager.GetString("FilterFunctionEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მეტია ვიდრე.
        /// </summary>
        internal static string FilterFunctionGreaterThan {
            get {
                return ResourceManager.GetString("FilterFunctionGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მეტია ან ტოლია ვიდრე.
        /// </summary>
        internal static string FilterFunctionGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterFunctionGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არის ცარიელი.
        /// </summary>
        internal static string FilterFunctionIsEmpty {
            get {
                return ResourceManager.GetString("FilterFunctionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არის ნალი.
        /// </summary>
        internal static string FilterFunctionIsNull {
            get {
                return ResourceManager.GetString("FilterFunctionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნაკლებია ვიდრე.
        /// </summary>
        internal static string FilterFunctionLessThan {
            get {
                return ResourceManager.GetString("FilterFunctionLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნაკლებია ან ტოლია ვიდრე.
        /// </summary>
        internal static string FilterFunctionLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterFunctionLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არ არის შორის.
        /// </summary>
        internal static string FilterFunctionNotBetween {
            get {
                return ResourceManager.GetString("FilterFunctionNotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არ არის ტოლი.
        /// </summary>
        internal static string FilterFunctionNotEqualTo {
            get {
                return ResourceManager.GetString("FilterFunctionNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არ არის ცარიელი.
        /// </summary>
        internal static string FilterFunctionNotIsEmpty {
            get {
                return ResourceManager.GetString("FilterFunctionNotIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არ არის ნალი.
        /// </summary>
        internal static string FilterFunctionNotIsNull {
            get {
                return ResourceManager.GetString("FilterFunctionNotIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to იწყება.
        /// </summary>
        internal static string FilterFunctionStartsWith {
            get {
                return ResourceManager.GetString("FilterFunctionStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to და.
        /// </summary>
        internal static string GroupOperationAnd {
            get {
                return ResourceManager.GetString("GroupOperationAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არა და.
        /// </summary>
        internal static string GroupOperationNotAnd {
            get {
                return ResourceManager.GetString("GroupOperationNotAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არა ან.
        /// </summary>
        internal static string GroupOperationNotOr {
            get {
                return ResourceManager.GetString("GroupOperationNotOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ან.
        /// </summary>
        internal static string GroupOperationOr {
            get {
                return ResourceManager.GetString("GroupOperationOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to წაშლა.
        /// </summary>
        internal static string RemoveToolTip {
            get {
                return ResourceManager.GetString("RemoveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გთხოვთ არ წაშალოთ გასაღები..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
    }
}
